export const areaCode = [
    { label: `United States`, value: '1' },
    { label: `China`, value: '86' },
    { label: `Malaysia`, value: '60' },
    { label: `Indonesia`, value: '62' },
    { label: `Philippines`, value: '63' },
    { label: `Singapore`, value: '65' },
    { label: `Thailand`, value: '66' },
    { label: `Brunei`, value: '673' },
    { label: `Japan`, value: '81' },
    { label: `South Korea`, value: '82' },
    { label: `Vietnam`, value: '84' },
    { label: `North Korea`, value: '850' },
    { label: `Hong Kong (China)`, value: '852' },
    { label: `Macao (China)`, value: '853' },
    { label: `Cambodia`, value: '855' },
    { label: `Laos`, value: '856' },
    { label: `Taiwan (China)`, value: '886' },
    { label: `Bangladesh`, value: '880' },
    { label: `Turkey`, value: '90' },
    { label: `India`, value: '91' },
    { label: `Pakistan`, value: '92' },
    { label: `Afghanistan`, value: '93' },
    { label: `Sri Lanka`, value: '94' },
    { label: `Myanmar`, value: '95' },
    { label: `Maldives`, value: '960' },
    { label: `Lebanon`, value: '961' },
    { label: `Jordan`, value: '962' },
    { label: `Syria`, value: '963' },
    { label: `Iraq`, value: '964' },
    { label: `Kuwait`, value: '965' },
    { label: `Saudi Arabia`, value: '966' },
    { label: `Oman`, value: '968' },
    { label: `Israel`, value: '972' },
    { label: `Bahrain`, value: '973' },
    { label: `Qatar`, value: '974' },
    { label: `Bhutan`, value: '975' },
    { label: `Mongolia`, value: '976' },
    { label: `Nepal`, value: '977' },
    { label: `Iran`, value: '98' },
    { label: `Cyprus`, value: '357' },
    { label: `Palestine`, value: '970' },
    { label: `UAE`, value: '971' },
    { label: `Russian Federation`, value: '7' },
    { label: `Greece`, value: '30' },
    { label: `Netherlands`, value: '31' },
    { label: `Belgium`, value: '32' },
    { label: `France`, value: '33' },
    { label: `Spain`, value: '34' },
    { label: `Gibraltar`, value: '350' },
    { label: `Portugal`, value: '351' },
    { label: `Luxembourg`, value: '352' },
    { label: `Ireland`, value: '353' },
    { label: `Iceland`, value: '354' },
    { label: `Albania`, value: '355' },
    { label: `Malta`, value: '356' },
    { label: `Andorra`, value: '376' },
    { label: `Finland`, value: '358' },
    { label: `Bulgaria`, value: '359' },
    { label: `Hungary`, value: '36' },
    { label: `Germany`, value: '49' },
    { label: `Yugoslavia`, value: '381' },
    { label: `Italy`, value: '39' },
    { label: `San Marino`, value: '378' },
    { label: `Vatican City 'Tigane`, value: '3906698' },
    { label: `Romania`, value: '40' },
    { label: `Switzerland`, value: '41' },
    { label: `Liechtenstein`, value: '423' },
    { label: `Austria`, value: '43' },
    { label: `United Kingdom`, value: '44' },
    { label: `Denmark`, value: '45' },
    { label: `Sweden`, value: '46' },
    { label: `Norway`, value: '47' },
    { label: `Poland`, value: '48' },
    { label: `Czech Republic`, value: '420' },
    { label: `Slovakia`, value: '421' },
    { label: `Monaco`, value: '377' },
    { label: `Macedonia`, value: '389' },
    { label: `Croatia`, value: '385' },
    { label: `Slovenia`, value: '386' },
    { label: `Bosnia and Zeegovina`, value: '387' },
    { label: `Republic of Armenia`, value: '374' },
    { label: `Republic of Belarus`, value: '375' },
    { label: `Republic of Georgia`, value: '995' },
    { label: `Republic of Kazakhstan`, value: '7' },
    { label: `Republic of Kyrgyzstan`, value: '996' },
    { label: `Republic of Uzbekistan`, value: '998' },
    { label: `Republic of Tajikistan`, value: '992' },
    { label: `Republic of Turkmenistan`, value: '993' },
    { label: ` Ukraine`, value: '380' },
    { label: `Lithuania`, value: '370' },
    { label: `Latvia`, value: '371' },
    { label: `Estonia`, value: '372' },
    { label: `Moldova`, value: '373' },
    { label: `Egypt`, value: '20' },
    { label: `Morocco`, value: '212' },
    { label: `Algeria`, value: '213' },
    { label: `Tunisia`, value: '216' },
    { label: `Libya`, value: '218' },
    { label: `Gambia`, value: '220' },
    { label: `Senegal`, value: '221' },
    { label: `Mauritania`, value: '222' },
    { label: `Mali`, value: '223' },
    { label: `Guinea`, value: '224' },
    { label: `Ivory Coast`, value: '225' },
    { label: `Burkina Faso`, value: '226' },
    { label: `Niger`, value: '227' },
    { label: `Togo`, value: '228' },
    { label: `Benin`, value: '229' },
    { label: `Mauritius`, value: '230' },
    { label: `Liberia`, value: '231' },
    { label: `Sierra Leone`, value: '232' },
    { label: `Ghana`, value: '233' },
    { label: `Nigeria`, value: '234' },
    { label: `Chad`, value: '235' },
    { label: `Central Africa`, value: '236' },
    { label: `Cameroon`, value: '237' },
    { label: `Cape Verde`, value: '238' },
    { label: `Sao Tome`, value: '239' },
    { label: `Principe`, value: '239' }
];
